### ISSUE TITLE
Document `pending` and `error` state

### ISSUE THREAD

**Issue by angelo-v** [solid/react-components#11]
### Motivation

I found out about the `pending` and `error` props that get passed to components wrapped by `evaluateExpressions` by looking at the code. 

### Proposal
Since those are quite useful they should be officially documented.

### Additional info
The `error` case does not work as I expected it to work, e.g. if a resources could not be found (404) my component just gets `pending=true` but not `error=true`. Due to the lack of documentation I cannot figure out if I am making false assumptions about when the `error` prop is set, or if there is an actual bug.

**Comment by RubenVerborgh** [comment]
@angelo-v Thanks for reporting.

> The `error` case does not work as I expected it to work, e.g. if a resources could not be found (404) my component just gets `pending=true` but not `error=true`.

@rubensworks We might need to check that in ldflex-comunica or Comunica itself.

**Comment by rubensworks** [comment]
It looks like Comunica is not properly handling 404's, created an issue for it: https://github.com/comunica/comunica/issues/381

**Comment by RubenVerborgh** [comment]
Addressed by 353ebfdc541974b8a4a35dce1f3d7f3e73fdadff.
