### ISSUE TITLE
Errors during building the `demo` app. 

### ISSUE THREAD

**Issue by aorumbayev** [solid/react-components#13]
I was trying to build a demo app when the following issue appeared. Am I using wrong package manager or a node version?

### How to reproduce
1. Clone the repository
2. Run `yarn install`
3. Run `yarn run demo`
4. See the following error : 

```bash
Creating a build of the demo app...
Failed to compile.

chunk main [entry]
index.js
Missing external configuration for type:commonjs2


error Command failed with exit code 1.
```

### Version information
- Node Version: `v10.14.2`
- yarn Version: `1.13.0`
- npm Version: `6.4.1`
- OS: `macOS v10.14.3` 
- Browser: `Chrome`
- Browser Version: `v72.0.3626.119`

**Comment by RubenVerborgh** [comment]
Can you try with `npm`?

**Comment by aorumbayev** [comment]
Hey, @RubenVerborgh I'm really sorry, my bad, I have this issue on [Inrupt's](https://github.com/Inrupt-inc/solid-react-components) repository, accidentally confused with this repo. 

Closing the issue now :-)

**Comment by RubenVerborgh** [comment]
No worries 🙂
