### ISSUE TITLE
Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by jairo-campos-JD** [solid/react-components#21]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function

### How to reproduce
1. Use LiveUpdate component in two different pages using React Router.
2. Go to page 1 then to page 2 more than 3 times (not browser reload) to unMounted LiveUpdate component.
3. A warning message will appear.

### Version information
- OS: iOS
- Browser: Chrome
- Browser Version: 75

### Additional info
Seems like it's an issue when WebSockets subscribe to a listener event, sometimes the unsubscribe event doesn't work.

**Comment by RubenVerborgh** [comment]
First suspicion is that React is too fast in firing the warning; unsubscription is Implemented (bur might be slightly delayed). Adding a mechanism to entirely prevent the warning, would probably cause more harm.

Closing, bit keeping for future reference. Thanks!
