### ISSUE TITLE
The README was not published with 1.7.0

### ISSUE THREAD

**Issue by Vinnl** [solid/react-components#22]
The [current npm page](https://www.npmjs.com/package/@solid/react/v/1.7.0) says "Unable to find a readme for @solid/react@1.7.0":

![image](https://user-images.githubusercontent.com/4251/64105970-86548880-cd77-11e9-9a9c-d6d57f289afe.png)

Even though 1.6.0 [did have one](https://www.npmjs.com/package/@solid/react/v/1.6.0).

**Comment by RubenVerborgh** [comment]
Reported npm bug: https://npm.community/t/readme-not-published-for-solid-react/9835

**Comment by Vinnl** [comment]
It's visible again now, so closing this.
