### ISSUE TITLE
Link to useful blog post in readme?

### ISSUE THREAD

**Issue by Vinnl** [solid/react-components#27]
### Motivation
It can be hard for people to find their way around LDFlex/`@solid/react`.

### Proposal
In e.g. the readme, link to [this blog post](https://trav.page/log/write-solid/) by @travis that provides some useful examples and lists some of the current limitations.

**Comment by RubenVerborgh** [comment]
@travis This is excellent work, thanks. We will list this.

**Comment by travis** [comment]
thank you, glad it's useful!
