### ISSUE TITLE
Breakage with LDflex 2.9.0: "Specify at least one value for the property"

### ISSUE THREAD

**Issue by NSeydoux** [solid/react-components#31]
When bumping `solid-auth-client` to be a wrapper around `solid-auth-fetcher`, some LDflex expressions present in the demo `@solid/react` components, such as `[https://ruben.verborgh.org/profile/#me].homepage`, throw the following error: `@solid/react-components Expression evaluation failed. Error: "Specify at least one value for the property"` instead of returning the expected value.

## How to reproduce

1. Clone `git@github.com:inrupt/react-components.git`
2. Checkout the `fix/ldfex-solid-auth-fetcher` branch
3. `npm ci`
4. `npm run start`
5. Open `http://localhost:8080` is a browser: the page should be blank, and the console should contain the errors.
6. If `(<Link href="[https://ruben.verborgh.org/profile/#me].homepage"/>)` is commented out of `demo/app.jsx`, then the page should be displayed (and `<Label src="https://ruben.verborgh.org/profile/#me"/>` actually works as expected)

## Version information
- Node.js Version: v12.12.0
- npm Version: 6.14.4
- OS: Ubuntu 18.04
- Browser: Firefox 77

## Additional info

- The bug may need to be eventually fixed in either LDflex or `solid-auth-fetcher` (probably the latter), but since the symptoms were observed when migrating `@solid/react`, I figured reporting it here would be the easiest.
- You might experience issues when logging in. I'm aware of the issue, and I'm currently fixing it, and it's not related to the problem described here.

**Comment by RubenVerborgh** [comment]
This is very likely unrelated to the fetcher, but rather to the latest LDflex version.

**Comment by RubenVerborgh** [comment]
@NSeydoux New functionality was introduced to mitigate this in `ldflex@2.10.0` and propagated to `@solid/query-ldflex@2.11.1`; updating `package-lock.json` (as done in the latest `master`) should be sufficient.

**Comment by NSeydoux** [comment]
Indeed, it seems resolved, thanks !

**Comment by TallTed** [comment]
@NSeydoux @RubenVerborgh -- It seems this should be closed, based on https://github.com/solid/react-components/issues/31#issuecomment-642321853?

**Comment by NSeydoux** [comment]
Indeed, but it looks like it was closed by @RubenVerborgh when he pointed out the fix, right ?

**Comment by TallTed** [comment]
D'oh! You're right. Comments after the closing threw me off.
