### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by dcalacci** [solid/react-components#39]
Hi, not a feature request but a question so I am eschewing the issue guidelines. 

Is this project considered active? I am interested in using solid in a react-native application for research but grokking the ecosystem here has proven challenging. 

Is this still considered the right library to use to build react apps that interact with solid using LDflex?

Thanks!

**Comment by RubenVerborgh** [comment]
Hi @dcalacci 

> Is this project considered active?

No active development is happening on this repository at the moment, but do have a look at https://solidproject.org/developers/tools/
