### ISSUE TITLE
Errors in Edge after polyfilling TextEncoder

### ISSUE THREAD

**Issue by bushidocodes** [solid/react-components#8]
Related to https://github.com/solid/solid-auth-client/issues/68
I am getting errors using seemingly valid LDflex paths in Edge after polyfilling TextEncoder.

### How to reproduce
1. Go to https://5bfb333de39e7c7ef76b9672--competent-babbage-885c43.netlify.com in Edge
2. Click on Login and login using your Solid provider
3. Click the black space between View and Logout where a button should rendered to load your profile
4. A broken profile viewer view will load
5. Open developer tools to see the error. The expressions are correct and follow your documentation. 

Error
```
@solid/react-components Expression evaluation failed. Error: src should be an LDflex path or string but is [https://bushidocodes.solid.community/profile/card#me].image
```
Associated Line of Code:
```jsx
<Image src={`[${decodeURIComponent(this.props.webid)}].image`} />
```

## Screenshots
![image](https://user-images.githubusercontent.com/8700322/48986366-f4ca3300-f0e1-11e8-962d-7b2a0f5dc28f.png)

### Version information
- Node.js Version: v11.2.0
- npm Version: 6.4.1
- OS: Windows 10
- Browser: Edge
- Browser Version: Microsoft Edge 42.17134.1.0

**Comment by RubenVerborgh** [comment]
Hi @bushidocodes,

Looks like a great app your're building, tried it in my browser.

Unfortunately, I'm not on Windows so I cannot test or fix.
I suspect this is also broken in our playground? https://solid.github.io/ldflex-playground/

What does the console window say? It should have a full stack trace of your problem.

Thanks,

Ruben

**Comment by RubenVerborgh** [comment]
Following up in https://github.com/solid/solid-auth-client/issues/68.
